In [1]:

from keras.models import load_model
import numpy as np
import cv2
model =load_model('mymodel.h5')

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [2]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [3]:
from skimage.transform import resize
import uuid 
def detect(frame):
    try:
        data=uuid.uuid1()
        img= resize(frame,(128,128))
        img = np.expand_dims(img,axis=0)
        if(np.max(img)>1):
            img =img/255.0
        prediction =model.predict(img)
        print (prediction)
        prediction_class = model.predict_classes(img)
        if(prediction_class[0]==0):
            print("elen")
            cv2.imwrite('C:/Users/Bindhu Ravindra/Documents/lalala/elen/_'+str(data)+'.jpeg', frame)
            
                
        if(prediction_class[0]==1):
            
            print("modi")
            cv2.imwrite('C:/Users/Bindhu Ravindra/Documents/lalala/modi/_'+str(data)+'.jpeg', frame)
        
    except AttributeError:
        print("shape not found")

In [4]:
frame= cv2.imread("test2.jpg")
data= detect(frame)

C:\Users\Bindhu Ravindra\Anaconda3\lib\site-packages\skimage\transform\_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
C:\Users\Bindhu Ravindra\Anaconda3\lib\site-packages\skimage\transform\_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "


[[0.46577045 0.53657955]]
modi


In [1]:
import numpy as np
from keras.preprocessing import image
from tkinter import *
from PIL import ImageTk, Image
from tkinter import filedialog
import os
from keras.models import load_model
model = load_model('mymodel.h5')
import cv2
from skimage.transform import resize

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [2]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [4]:
root = Tk()
root.geometry("550x300+300+150")
root.resizable(width=True, height=True)

def openfn():
    filename = filedialog.askopenfilename(title='open')
    return filename
def open_img():
    x = openfn()
    frame= cv2.imread(x)
    img= resize(frame,(128,128))
    img = np.expand_dims(img,axis=0)
    if(np.max(img)>1):
        img =img/255.0
    prediction =model.predict(img)
    print (prediction)
    prediction_class = model.predict_classes(img)
    index=["elen","modi"]
    label = Label( root, text="Prediction : "+index[prediction_class[0]])
    label.pack()
    img = Image.open(x)
    img = img.resize((250, 250), Image.ANTIALIAS)
    img = ImageTk.PhotoImage(img)
    panel = Label(root, image=img)
    panel.image = img
    panel.pack()

btn = Button(root, text='open image', command=open_img).pack()

root.mainloop()


[[0.4657975 0.5365544]]
[[0.56407183 0.45901042]]
